package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * BaseManage generated by hbm2java
 */
public class Base implements java.io.Serializable {

	private BigDecimal baseId;
	private String baseName;
	private BigDecimal departmentId;

	public Base() {
	}

	public Base(BigDecimal baseId, String baseName,
			BigDecimal departmentId) {
		this.baseId = baseId;
		this.baseName = baseName;
		this.departmentId = departmentId;
	}

	public BigDecimal getBaseId() {
		return this.baseId;
	}

	public void setBaseId(BigDecimal baseId) {
		this.baseId = baseId;
	}

	public String getBaseName() {
		return this.baseName;
	}

	public void setBaseName(String baseName) {
		this.baseName = baseName;
	}

	public BigDecimal getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(BigDecimal departmentId) {
		this.departmentId = departmentId;
	}

}
