package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * DepartmentManage generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private BigDecimal departmentId;
	private String departmentName;
	private BigDecimal managerId;
	private BigDecimal projectId;
	private String note;

	public Department() {
	}

	public Department(BigDecimal departmentId, String departmentName,
			BigDecimal managerId, BigDecimal projectId) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.managerId = managerId;
		this.projectId = projectId;
	}

	public Department(BigDecimal departmentId, String departmentName,
			BigDecimal managerId, BigDecimal projectId, String note) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.managerId = managerId;
		this.projectId = projectId;
		this.note = note;
	}

	public BigDecimal getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(BigDecimal departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public BigDecimal getManagerId() {
		return this.managerId;
	}

	public void setManagerId(BigDecimal managerId) {
		this.managerId = managerId;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
