package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

/**
 * RecreationalActivites generated by hbm2java
 */
public class RecreationalActivite implements java.io.Serializable {

	private RecreationalActiviteId id;

	public RecreationalActivite() {
	}

	public RecreationalActivite(RecreationalActiviteId id) {
		this.id = id;
	}

	public RecreationalActiviteId getId() {
		return this.id;
	}

	public void setId(RecreationalActiviteId id) {
		this.id = id;
	}

}
