package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * RecreationalActivitesId generated by hbm2java
 */
public class RecreationalActiviteId implements java.io.Serializable {

	private BigDecimal pecreationalId;
	private String recreationalName;
	private BigDecimal projectId;
	private BigDecimal recreationalAttribute;
	private Date activitiesDate;
	private String activitiesPlace;
	private String note;

	public RecreationalActiviteId() {
	}

	public RecreationalActiviteId(BigDecimal pecreationalId,
			String recreationalName, BigDecimal projectId,
			BigDecimal recreationalAttribute, Date activitiesDate,
			String activitiesPlace) {
		this.pecreationalId = pecreationalId;
		this.recreationalName = recreationalName;
		this.projectId = projectId;
		this.recreationalAttribute = recreationalAttribute;
		this.activitiesDate = activitiesDate;
		this.activitiesPlace = activitiesPlace;
	}

	public RecreationalActiviteId(BigDecimal pecreationalId,
			String recreationalName, BigDecimal projectId,
			BigDecimal recreationalAttribute, Date activitiesDate,
			String activitiesPlace, String note) {
		this.pecreationalId = pecreationalId;
		this.recreationalName = recreationalName;
		this.projectId = projectId;
		this.recreationalAttribute = recreationalAttribute;
		this.activitiesDate = activitiesDate;
		this.activitiesPlace = activitiesPlace;
		this.note = note;
	}

	public BigDecimal getPecreationalId() {
		return this.pecreationalId;
	}

	public void setPecreationalId(BigDecimal pecreationalId) {
		this.pecreationalId = pecreationalId;
	}

	public String getRecreationalName() {
		return this.recreationalName;
	}

	public void setRecreationalName(String recreationalName) {
		this.recreationalName = recreationalName;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public BigDecimal getRecreationalAttribute() {
		return this.recreationalAttribute;
	}

	public void setRecreationalAttribute(BigDecimal recreationalAttribute) {
		this.recreationalAttribute = recreationalAttribute;
	}

	public Date getActivitiesDate() {
		return this.activitiesDate;
	}

	public void setActivitiesDate(Date activitiesDate) {
		this.activitiesDate = activitiesDate;
	}

	public String getActivitiesPlace() {
		return this.activitiesPlace;
	}

	public void setActivitiesPlace(String activitiesPlace) {
		this.activitiesPlace = activitiesPlace;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecreationalActiviteId))
			return false;
		RecreationalActiviteId castOther = (RecreationalActiviteId) other;

		return ((this.getPecreationalId() == castOther.getPecreationalId()) || (this
				.getPecreationalId() != null
				&& castOther.getPecreationalId() != null && this
				.getPecreationalId().equals(castOther.getPecreationalId())))
				&& ((this.getRecreationalName() == castOther
						.getRecreationalName()) || (this.getRecreationalName() != null
						&& castOther.getRecreationalName() != null && this
						.getRecreationalName().equals(
								castOther.getRecreationalName())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this
						.getProjectId() != null
						&& castOther.getProjectId() != null && this
						.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getRecreationalAttribute() == castOther
						.getRecreationalAttribute()) || (this
						.getRecreationalAttribute() != null
						&& castOther.getRecreationalAttribute() != null && this
						.getRecreationalAttribute().equals(
								castOther.getRecreationalAttribute())))
				&& ((this.getActivitiesDate() == castOther.getActivitiesDate()) || (this
						.getActivitiesDate() != null
						&& castOther.getActivitiesDate() != null && this
						.getActivitiesDate().equals(
								castOther.getActivitiesDate())))
				&& ((this.getActivitiesPlace() == castOther
						.getActivitiesPlace()) || (this.getActivitiesPlace() != null
						&& castOther.getActivitiesPlace() != null && this
						.getActivitiesPlace().equals(
								castOther.getActivitiesPlace())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null
						&& castOther.getNote() != null && this.getNote()
						.equals(castOther.getNote())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPecreationalId() == null ? 0 : this.getPecreationalId()
						.hashCode());
		result = 37
				* result
				+ (getRecreationalName() == null ? 0 : this
						.getRecreationalName().hashCode());
		result = 37 * result
				+ (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37
				* result
				+ (getRecreationalAttribute() == null ? 0 : this
						.getRecreationalAttribute().hashCode());
		result = 37
				* result
				+ (getActivitiesDate() == null ? 0 : this.getActivitiesDate()
						.hashCode());
		result = 37
				* result
				+ (getActivitiesPlace() == null ? 0 : this.getActivitiesPlace()
						.hashCode());
		result = 37 * result
				+ (getNote() == null ? 0 : this.getNote().hashCode());
		return result;
	}

}
