package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * ScientificResarchAchievement generated by hbm2java
 */
public class ScientificResarchAchievement implements java.io.Serializable {

	private BigDecimal achievementId;
	private String achievementName;
	private BigDecimal projectId;
	private BigDecimal appraisal;
	private String appraisalExpertImformation;
	private String prize;
	private String note;

	public ScientificResarchAchievement() {
	}

	public ScientificResarchAchievement(BigDecimal achievementId,
			String achievementName, BigDecimal projectId, BigDecimal appraisal,
			String appraisalExpertImformation) {
		this.achievementId = achievementId;
		this.achievementName = achievementName;
		this.projectId = projectId;
		this.appraisal = appraisal;
		this.appraisalExpertImformation = appraisalExpertImformation;
	}

	public ScientificResarchAchievement(BigDecimal achievementId,
			String achievementName, BigDecimal projectId, BigDecimal appraisal,
			String appraisalExpertImformation, String prize, String note) {
		this.achievementId = achievementId;
		this.achievementName = achievementName;
		this.projectId = projectId;
		this.appraisal = appraisal;
		this.appraisalExpertImformation = appraisalExpertImformation;
		this.prize = prize;
		this.note = note;
	}

	public BigDecimal getAchievementId() {
		return this.achievementId;
	}

	public void setAchievementId(BigDecimal achievementId) {
		this.achievementId = achievementId;
	}

	public String getAchievementName() {
		return this.achievementName;
	}

	public void setAchievementName(String achievementName) {
		this.achievementName = achievementName;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public BigDecimal getAppraisal() {
		return this.appraisal;
	}

	public void setAppraisal(BigDecimal appraisal) {
		this.appraisal = appraisal;
	}

	public String getAppraisalExpertImformation() {
		return this.appraisalExpertImformation;
	}

	public void setAppraisalExpertImformation(String appraisalExpertImformation) {
		this.appraisalExpertImformation = appraisalExpertImformation;
	}

	public String getPrize() {
		return this.prize;
	}

	public void setPrize(String prize) {
		this.prize = prize;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
