package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * ScientificResearcProject generated by hbm2java
 */
public class ScientificResearcProject implements java.io.Serializable {

	private BigDecimal projectId;
	private String projectName;
	private BigDecimal projectFund;
	private BigDecimal projectAttribute;
	private String fundOrigin;
	private String projectClass;
	private BigDecimal contractFund;
	private String note;

	public ScientificResearcProject() {
	}

	public ScientificResearcProject(BigDecimal projectId, String projectName,
			BigDecimal projectFund, BigDecimal projectAttribute,
			String fundOrigin, String projectClass, BigDecimal contractFund) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectFund = projectFund;
		this.projectAttribute = projectAttribute;
		this.fundOrigin = fundOrigin;
		this.projectClass = projectClass;
		this.contractFund = contractFund;
	}

	public ScientificResearcProject(BigDecimal projectId, String projectName,
			BigDecimal projectFund, BigDecimal projectAttribute,
			String fundOrigin, String projectClass, BigDecimal contractFund,
			String note) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectFund = projectFund;
		this.projectAttribute = projectAttribute;
		this.fundOrigin = fundOrigin;
		this.projectClass = projectClass;
		this.contractFund = contractFund;
		this.note = note;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public BigDecimal getProjectFund() {
		return this.projectFund;
	}

	public void setProjectFund(BigDecimal projectFund) {
		this.projectFund = projectFund;
	}

	public BigDecimal getProjectAttribute() {
		return this.projectAttribute;
	}

	public void setProjectAttribute(BigDecimal projectAttribute) {
		this.projectAttribute = projectAttribute;
	}

	public String getFundOrigin() {
		return this.fundOrigin;
	}

	public void setFundOrigin(String fundOrigin) {
		this.fundOrigin = fundOrigin;
	}

	public String getProjectClass() {
		return this.projectClass;
	}

	public void setProjectClass(String projectClass) {
		this.projectClass = projectClass;
	}

	public BigDecimal getContractFund() {
		return this.contractFund;
	}

	public void setContractFund(BigDecimal contractFund) {
		this.contractFund = contractFund;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
