package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * TotalCardManage generated by hbm2java
 */
public class TotalCard implements java.io.Serializable {

	private BigDecimal cardId;
	private BigDecimal projectId;
	private BigDecimal inclusionFund;
	private BigDecimal cardAttribute;
	private String note;

	public TotalCard() {
	}

	public TotalCard(BigDecimal cardId, BigDecimal projectId,
			BigDecimal cardAttribute) {
		this.cardId = cardId;
		this.projectId = projectId;
		this.cardAttribute = cardAttribute;
	}

	public TotalCard(BigDecimal cardId, BigDecimal projectId,
			BigDecimal inclusionFund, BigDecimal cardAttribute, String note) {
		this.cardId = cardId;
		this.projectId = projectId;
		this.inclusionFund = inclusionFund;
		this.cardAttribute = cardAttribute;
		this.note = note;
	}

	public BigDecimal getCardId() {
		return this.cardId;
	}

	public void setCardId(BigDecimal cardId) {
		this.cardId = cardId;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public BigDecimal getInclusionFund() {
		return this.inclusionFund;
	}

	public void setInclusionFund(BigDecimal inclusionFund) {
		this.inclusionFund = inclusionFund;
	}

	public BigDecimal getCardAttribute() {
		return this.cardAttribute;
	}

	public void setCardAttribute(BigDecimal cardAttribute) {
		this.cardAttribute = cardAttribute;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
