package jaunty.rpm.bean;

// Generated Dec 1, 2010 8:29:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * UserManager generated by hbm2java
 */
public class User implements java.io.Serializable {

	private BigDecimal userid;
	private String password;
	private String username;
	private BigDecimal departmentId;
	private BigDecimal permission;
	private BigDecimal projectId;
	private String note;

	public User() {
	}

	public User(BigDecimal userid, String password, String username,
			BigDecimal departmentId, BigDecimal permission, BigDecimal projectId) {
		this.userid = userid;
		this.password = password;
		this.username = username;
		this.departmentId = departmentId;
		this.permission = permission;
		this.projectId = projectId;
	}

	public User(BigDecimal userid, String password, String username,
			BigDecimal departmentId, BigDecimal permission,
			BigDecimal projectId, String note) {
		this.userid = userid;
		this.password = password;
		this.username = username;
		this.departmentId = departmentId;
		this.permission = permission;
		this.projectId = projectId;
		this.note = note;
	}

	public BigDecimal getUserid() {
		return this.userid;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public BigDecimal getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(BigDecimal departmentId) {
		this.departmentId = departmentId;
	}

	public BigDecimal getPermission() {
		return this.permission;
	}

	public void setPermission(BigDecimal permission) {
		this.permission = permission;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
